class DeviceConfig:
    WIFI_SSID = "YOUR_WIFI_SSID"
    WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
    BACKEND_BASE_URL = "http://192.168.1.100:5000"
    DEVICE_ID = "esp32cam-lab-01"
    DEVICE_API_KEY = "demo-device-key"
    FIRMWARE_VERSION = "v1.0.0-python"

    WIFI_CONNECT_TIMEOUT_MS = 20000
    HEARTBEAT_INTERVAL_MS = 15000
    COMMAND_POLL_INTERVAL_MS = 5000
    QR_SCAN_INTERVAL_MS = 2000
    FACE_CAPTURE_DELAY_MS = 1000
    FINGERPRINT_TIMEOUT_MS = 10000
    STATE_TIMEOUT_MS = 15000
    RELAY_PULSE_MS = 2000

    JPEG_QUALITY = 12
    FRAME_SIZE = "VGA"

    RELAY_ACTIVE_HIGH = True
    ENABLE_STATUS_WEB = True
    ENABLE_EXTERNAL_STATUS_LED = False

    STATUS_WEB_PORT = 80
    STORAGE_PATH = "attendance_store.json"
